In [2]:
import numpy as np
"""
f(x) = a +2b + 3c +4d -30
"""
# Inisialiasi  jumlah populasi, jumlah gen
jml_populasi = 6
jml_gen = 4

kromosom = np.random.randint(0,30 ,(jml_populasi,jml_gen))
print("Kromosom :",kromosom)

epoch = 0

while epoch <  jml_populasi :
    # penjumlahan fungsi objektif
    fo = abs((kromosom[:,0] + 2*kromosom[:,1] + 3*kromosom[:,2] + 4*kromosom[:,3]) - 30 )
    print("Fungsi objektif kromosom :", fo)
    
    #total fungsi objektif
    total_fo = fo.sum()
    print("Total fungsi objectif : ", total_fo)
    
    #rata - rata fungsi objektif
    rata2 = total_fo/jml_populasi
    print("Rata - rata fungsi objektif : ",rata2 )
    
    # Seleksi fitness kromosom
    fitness =  1/(1 + fo)
    print("Fitness :",fitness)
    
    # fungsi penjumlahan total fitness
    total = fitness.sum()
    print("Total Fitness :",total)
    
    # penjumlahan probabilitas setiap kromosom
    prob = fitness/total
    print("Probabilitas :",prob)
    
    # seleksi menggunakan Roulette Wheel dan penjumlahan komulatif probabilitas
    C = np.cumsum(prob)
    print("Penjumlahan Komulatif :", C)
    
    # membuat Random Numbers pada range 0-1
    Random_num = np.random.random((kromosom.shape[0]))
    print("Random Numbers :",Random_num)
    
    # Membuat matrik kromosom baru
    kromosom2 = np.zeros((kromosom.shape[0],jml_gen))
    
    for i in range(Random_num.shape[0]):
        for j in range(kromosom.shape[0]):
            if Random_num[i]  < C[j]:
                kromosom2[i,:] = kromosom[j,:]
                break
            
    kromosom = kromosom2
    print("Kromosom Baru :",kromosom)
        
    # crossover
    R = [np.random.random() for i in range(jml_populasi)]
    print("Nilai Random :",R)
    
    # Crossover Rate
    pc = 0.25
    flag = Random_num < pc
    print("Flagged Values :",flag)
    
    # Menentukan Kromosom Silang
    # Jika Random Numbers kurang dari crossover rate (0.25) maka True
    kromosom_silang = kromosom[[(i == True) for i in flag]]
    print("Kromosom Silang :",kromosom_silang)
    panjang_krom_silang = len(kromosom_silang)
    
    # Menjumlahkan nilai silang
    nilai_silang = np.random.randint(1,3,panjang_krom_silang)
    print("Nilai Silang :",nilai_silang)
    
    copy_kromosom = np.zeros(kromosom_silang.shape)
    
    
    # Copy nilai kromosom untuk penjumlahan
    for i in range(kromosom_silang.shape[0]):
        copy_kromosom[i , :] = kromosom_silang[i , :]
        
    if panjang_krom_silang == 1:
        kromosom_silang = kromosom_silang
    else :
        for i in range(panjang_krom_silang):
            c_val = nilai_silang[i]
            if i == panjang_krom_silang - 1 :
                kromosom_silang[i , c_val:] = copy_kromosom[0 , c_val:]
            else :
                kromosom_silang[i , c_val:] = copy_kromosom[i+1 , c_val:]
        
    print("Kromosom Silang:",kromosom_silang)
    
    index_kromosom = 0
    index_kromosom_baru = 0
    for i in flag :
        if i == True :
            kromosom[index_kromosom, :] = kromosom_silang[index_kromosom_baru, :]
            index_kromosom_baru = index_kromosom_baru + 1
        index_kromosom = index_kromosom + 1 
    
    print("Kromosom Baru:", kromosom)
    
    # Mejumlahkan total generation
    a ,b = kromosom.shape[0] ,kromosom.shape[1]
    total_gen = a*b
    print("Total Generations :",total_gen)
    
    #rate mutasi = pm
    pm = 0.1
    no_of_mutations = int(np.round(pm * total_gen))
    print("Jumlah mutasi :" ,no_of_mutations)
    
    # Penjumlahan angka generasi
    gen_num = np.random.randint(0,total_gen - 1, no_of_mutations)
    print(" Menentukan Angka Random : " , gen_num)
    
    # Menentukan angka random yang akan menggantikan kromosom yang terseleksi untuk dimutasi
    Replacing_num = np.random.randint(0,30, no_of_mutations)
    print(" Angka yang akan digantikan : " , Replacing_num)
    
    for i in range(no_of_mutations):
        a = gen_num[i]
        row = a//4
        col = a%4
        kromosom[row , col] = Replacing_num[i]
    
    print(" Kromosom Setelah Mutasi : " , kromosom)
  
    epoch = epoch + 1


Kromosom : [[15  4 29  4]
 [25 26 12 11]
 [ 1 29  6 29]
 [21  9  7  8]
 [23  2 28  7]
 [12  6  6 24]]
Fungsi objektif kromosom : [ 96 127 163  62 109 108]
Total fungsi objectif :  665
Rata - rata fungsi objektif :  110.83333333333333
Fitness : [0.01030928 0.0078125  0.00609756 0.01587302 0.00909091 0.00917431]
Total Fitness : 0.05835757621665569
Probabilitas : [0.17665707 0.13387293 0.10448619 0.2719958  0.15577942 0.15720858]
Penjumlahan Komulatif : [0.17665707 0.31053    0.4150162  0.687012   0.84279142 1.        ]
Random Numbers : [0.58927011 0.53442612 0.71561455 0.35359037 0.34877913 0.53305731]
Kromosom Baru : [[21.  9.  7.  8.]
 [21.  9.  7.  8.]
 [23.  2. 28.  7.]
 [ 1. 29.  6. 29.]
 [ 1. 29.  6. 29.]
 [21.  9.  7.  8.]]
Nilai Random : [0.699871814262984, 0.9091399927205065, 0.1385885111139501, 0.9059974305062742, 0.7636586548715625, 0.7204143217091225]
Flagged Values : [False False False False False False]
Kromosom Silang : []
Nilai Silang : []
Kromosom Silang: []
Kromosom Bar